name: Meson node  #name of node
on:
  - push
permissions: write-all
jobs:
  meson:
    runs-on: ubuntu-latest
    defaults:
      run:
       shell: bash
       
    steps:
      - name: Checkout Repo
        uses: actions/checkout@main
      
      - name: Push changes
        uses: actions/checkout@v2
        with:
          repository: Github-Username/meson
          token: ${{secrets.ACCESSTOKEN}}
 
      - run: script/download.sh
        
