name: Meson node  #name of node
on:
  - push
permissions: write-all
jobs:
  meson:
    runs-on: ubuntu-latest
    defaults:
      run:
       shell: bash
       
    steps:
    - uses: actions/checkout@v2
      with:
          repository: superdeen/meson
          token: ${{secrets.ACCESSTOKEN}}

    - run: script/download.sh
        
